# mengisi nilai dari variabel dari keyboard menggunakan fungsi input ()
var1 = input("masukkan angka 1= ")
var2 = input("masukkan angka 2= ")
print("Hasil inputan = ", var1)
print("Hasil inputan = ", var2)